-- local sox = require("modules.sox")
local hyper = require("modules.hyper")
local bar = require("modules.sketchybar")
local app = require("modules.app")
local tft = require("modules.tft")
local mic = require("modules.mic")
local caffeine = require("modules.caffeine")
local util = require("util")
local sketchybar = require("modules.sketchybar")
-- local network = require("modules.network")

require("hs.ipc")
hs.loadSpoon("MenuExtraTrigger")
hs.loadSpoon("EmmyLua")

hs.hotkey.bind(util.hyper, "R", function()
	hs.reload()
	bar.reload()
	hs.execute("aerospace reload-config", true)
end)

hyper.init()
caffeine.init()
tft.init()
mic.init()
app.init()
-- sox.init()
sketchybar.init()

hs.hotkey.bind({}, "f13", function()
	hs.urlevent.openURL("obsidian://quickadd?choice=%E2%9C%8F%EF%B8%8F%20Tas")
end)

-- hs.audiodevice.watcher.setCallback(util.combineFns({ sox.watcherCallback, mic.watcherCallback }))
-- hs.audiodevice.watcher.start()

hs.notify.show("Hammerspoon", "", "Hammerspoon reloaded")
