local sox = require("modules.sox")
local bar = require("modules.sketchybar")
local app = require("modules.app")
local tft = require("modules.tft")
local mic = require("modules.mic")
local caffeine = require("modules.caffeine")
local kvm = require("modules.kvm")
local hub = require("modules.hub")
local util = require("util")
local sketchybar = require("modules.sketchybar")
-- local network = require("modules.network")

require("hs.ipc")
hs.loadSpoon("MenuExtraTrigger")
hs.loadSpoon("EmmyLua")

hs.hotkey.bind(util.hyper, "R", function()
	hs.reload()
	bar.reload()
	hs.execute("aerospace reload-config", true)
end)

caffeine.init()
tft.init()
mic.init()
app.init()
sox.init()
kvm.init()
sketchybar.init()

hub.init({ kvm.start }, { kvm.stop })

hs.audiodevice.watcher.setCallback(util.combineFns({ sox.watcherCallback, mic.watcherCallback }))
hs.audiodevice.watcher.start()

hs.notify.show("Hammerspoon", "", "Hammerspoon reloaded")
